# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-08 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0003_auto_20210508_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
